[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
basic_dapp = "BtbH9LjA9Y6sfiP5bzKEzPpGhX9MyXEjf99zkDnKpPDz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/brettgalvez/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
